# Generated by Django 5.2.4 on 2025-08-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('shop_owner', 'Shop Owner'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
